-- Sample data for Shopizer: Categories, Products, Customers, and Reviews
-- This script assumes the base initialization has already run

-- Insert Category
INSERT INTO SALESMANAGER.CATEGORY (CATEGORY_ID, CATEGORY_STATUS, SORT_ORDER, CATEGORY_IMAGE, CODE, VISIBLE, MERCHANT_ID, DEPTH, LINEAGE, DATE_CREATED, DATE_MODIFIED)
VALUES (100, 1, 0, NULL, 'electronics', 1, 1, 0, '/100/', NOW(), NOW());

INSERT INTO SALESMANAGER.CATEGORY_DESCRIPTION (DESCRIPTION_ID, CATEGORY_HIGHLIGHT, CATEGORY_ID, LANGUAGE_ID, NAME, DESCRIPTION, SEF_URL, TITLE, DATE_CREATED, DATE_MODIFIED)
VALUES (100, NULL, 100, 1, 'Electronics', 'Electronic products and gadgets', 'electronics', 'Electronics', NOW(), NOW());

-- Insert Customers
INSERT INTO SALESMANAGER.CUSTOMER (CUSTOMER_ID, CUSTOMER_GENDER, DATE_OF_BIRTH, EMAIL_ADDRESS, NICK, PASSWORD, ANONYMOUS, COMPANY, MERCHANT_ID, DEFAULT_LANGUAGE_ID, DATE_CREATED, DATE_MODIFIED)
VALUES 
(100, 'M', NULL, 'john.doe@example.com', 'johndoe', '$2a$10$dummypasswordhash', 0, NULL, 1, 1, NOW(), NOW()),
(101, 'F', NULL, 'jane.smith@example.com', 'janesmith', '$2a$10$dummypasswordhash', 0, NULL, 1, 1, NOW(), NOW()),
(102, 'M', NULL, 'mike.wilson@example.com', 'mikewilson', '$2a$10$dummypasswordhash', 0, NULL, 1, 1, NOW(), NOW());

INSERT INTO SALESMANAGER.CUSTOMER_BILLING (CUSTOMER_ID, BILLING_FIRST_NAME, BILLING_LAST_NAME, BILLING_STREET_ADDRESS, BILLING_CITY, BILLING_POSTCODE, BILLING_COUNTRY_ID, BILLING_ZONE_ID)
VALUES 
(100, 'John', 'Doe', '123 Main St', 'Montreal', 'H1H1H1', 38, 1403),
(101, 'Jane', 'Smith', '123 Main St', 'Montreal', 'H1H1H1', 38, 1403),
(102, 'Mike', 'Wilson', '123 Main St', 'Montreal', 'H1H1H1', 38, 1403);

INSERT INTO SALESMANAGER.CUSTOMER_DELIVERY (CUSTOMER_ID, DELIVERY_STREET_ADDRESS, DELIVERY_CITY, DELIVERY_POSTCODE, DELIVERY_COUNTRY_ID, DELIVERY_ZONE_ID)
VALUES 
(100, '123 Main St', 'Montreal', 'H1H1H1', 38, 1403),
(101, '123 Main St', 'Montreal', 'H1H1H1', 38, 1403),
(102, '123 Main St', 'Montreal', 'H1H1H1', 38, 1403);

-- Insert Products
INSERT INTO SALESMANAGER.PRODUCT (PRODUCT_ID, DATE_AVAILABLE, AVAILABLE, PRODUCT_HEIGHT, PRODUCT_LENGTH, PRODUCT_WEIGHT, PRODUCT_WIDTH, SKU, PREORDER, MERCHANT_ID, MANUFACTURER_ID, PRODUCT_TYPE_ID, DATE_CREATED, DATE_MODIFIED)
VALUES 
(100, NOW(), 1, NULL, NULL, NULL, NULL, 'LAPTOP-001', 0, 1, 1, 1, NOW(), NOW()),
(101, NOW(), 1, NULL, NULL, NULL, NULL, 'PHONE-001', 0, 1, 1, 1, NOW(), NOW()),
(102, NOW(), 1, NULL, NULL, NULL, NULL, 'TABLET-001', 0, 1, 1, 1, NOW(), NOW());

INSERT INTO SALESMANAGER.PRODUCT_DESCRIPTION (DESCRIPTION_ID, PRODUCT_HIGHLIGHT, PRODUCT_ID, LANGUAGE_ID, NAME, DESCRIPTION, SEF_URL, TITLE, DOWNLOAD, DATE_CREATED, DATE_MODIFIED)
VALUES 
(100, NULL, 100, 1, 'Premium Laptop', 'High-performance laptop with 16GB RAM and 512GB SSD', 'premium-laptop', 'Premium Laptop', NULL, NOW(), NOW()),
(101, NULL, 101, 1, 'Smartphone Pro', 'Latest smartphone with advanced camera and 5G connectivity', 'smartphone-pro', 'Smartphone Pro', NULL, NOW(), NOW()),
(102, NULL, 102, 1, 'Tablet Ultra', '10-inch tablet with stunning display and long battery life', 'tablet-ultra', 'Tablet Ultra', NULL, NOW(), NOW());

-- Link Products to Category
INSERT INTO SALESMANAGER.PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_ID)
VALUES 
(100, 100),
(101, 100),
(102, 100);

-- Insert Product Availability
INSERT INTO SALESMANAGER.PRODUCT_AVAILABILITY (PRODUCT_AVAIL_ID, PRODUCT_QUANTITY, PRODUCT_DATE_AVAILABLE, REGION, PRODUCT_ID, DATE_CREATED, DATE_MODIFIED)
VALUES 
(100, 50, NOW(), '*', 100, NOW(), NOW()),
(101, 100, NOW(), '*', 101, NOW(), NOW()),
(102, 75, NOW(), '*', 102, NOW(), NOW());

-- Insert Product Prices
INSERT INTO SALESMANAGER.PRODUCT_PRICE (PRODUCT_PRICE_ID, PRODUCT_PRICE_AMOUNT, DEFAULT_PRICE, PRODUCT_AVAIL_ID, DATE_CREATED, DATE_MODIFIED)
VALUES 
(100, 999.99, 1, 100, NOW(), NOW()),
(101, 699.99, 1, 101, NOW(), NOW()),
(102, 449.99, 1, 102, NOW(), NOW());

INSERT INTO SALESMANAGER.PRODUCT_PRICE_DESCRIPTION (PRICE_DESCRIPTION_ID, PRODUCT_PRICE_ID, LANGUAGE_ID, NAME, DATE_CREATED, DATE_MODIFIED)
VALUES 
(100, 100, 1, 'Base price', NOW(), NOW()),
(101, 101, 1, 'Base price', NOW(), NOW()),
(102, 102, 1, 'Base price', NOW(), NOW());

-- Insert Product Reviews
INSERT INTO SALESMANAGER.PRODUCT_REVIEW (PRODUCT_REVIEW_ID, REVIEWS_RATING, REVIEWS_READ, REVIEW_DATE, STATUS, CUSTOMERS_ID, PRODUCT_ID, DATE_CREATED, DATE_MODIFIED)
VALUES 
(100, 5.0, 0, NOW(), 1, 100, 100, NOW(), NOW()),
(101, 4.5, 0, NOW(), 1, 101, 101, NOW(), NOW()),
(102, 4.0, 0, NOW(), 1, 102, 102, NOW(), NOW());

INSERT INTO SALESMANAGER.PRODUCT_REVIEW_DESCRIPTION (DESCRIPTION_ID, PRODUCT_REVIEW_ID, LANGUAGE_ID, NAME, DESCRIPTION, DATE_CREATED, DATE_MODIFIED)
VALUES 
(100, 100, 1, 'Excellent product!', 'This product exceeded my expectations. Highly recommended!', NOW(), NOW()),
(101, 101, 1, 'Very good quality', 'Great value for money. Fast shipping and well packaged.', NOW(), NOW()),
(102, 102, 1, 'Good purchase', 'Satisfied with the product. Works as described.', NOW(), NOW());
